"use strict";
const fs=require("fs"),vm=require("vm"),assert=require("assert");
const ids=["searchInput","providerFilter","familyFilter","capabilityFilter","priceTypeFilter","newnessFilter","contextFilter","outputFilter","availabilityFilter","latencyFilter","uncensoredFilter","costFilter","costFilterValue","pageSize","pagination","modelCount","modelMeta","benchmarkTable thead","benchmarkTable tbody","selectionStatus","podium","insightList","radarChart","scatterChart","lineChart","lastUpdated","apiKey","promptInput","results","catalogStatus","loadModels","runPrompt","clearFilters","refreshButton","themeButton","explainButton","methodDialog"];
const node=()=>({value:"all",innerHTML:"",textContent:"",disabled:false,options:[],classList:{toggle(){}},addEventListener(){},insertAdjacentHTML(){},showModal(){},close(){}});
const nodes=new Map(ids.map(id=>[id,node()]));nodes.get("searchInput").value="";nodes.get("apiKey").value="test-key";nodes.get("promptInput").value="test";nodes.get("costFilter").value="100";nodes.get("contextFilter").value="0";nodes.get("outputFilter").value="0";nodes.get("pageSize").value="15";
const document={body:{classList:{toggle(){}}},querySelector(s){const id=s.replace(/^#/,"");if(!nodes.has(id))nodes.set(id,node());return nodes.get(id)},querySelectorAll(){return[]}};
const payload={data:[{id:"provider/live-model",name:"Live Model 70B",context_length:128000,created:1790000000,architecture:{input_modalities:["text"],output_modalities:["text"]},supported_parameters:["tools","response_format"],top_provider:{max_completion_tokens:8192},pricing:{prompt:"0.000001",completion:"0.000002"}},{id:"provider/second-model",name:"Second Model",context_length:64000,pricing:{prompt:"0.0000005",completion:"0.000001"}}]};
const context={document,Intl,Date,Math,String,Object,Array,Set,Promise,console,alert(){},fetch:async()=>({ok:true,json:async()=>payload})};
(async()=>{vm.runInNewContext(fs.readFileSync("app.js","utf8"),context);assert.match(nodes.get("podium").innerHTML,/Catalogo live/);assert.match(nodes.get("radarChart").innerHTML,/<svg/);assert.match(nodes.get("radarChart").innerHTML,/BENCH/);assert.equal(nodes.get("callCount").textContent,"00");assert.equal(nodes.get("latencyValue").textContent,"N/D");await context.loadModels();assert.match(nodes.get("benchmarkTable tbody").innerHTML,/Live Model/);assert.match(nodes.get("benchmarkTable tbody").innerHTML,/N\/D/);assert.match(nodes.get("catalogStatus").textContent,/2 modelli/);assert.match(nodes.get("radarChart").innerHTML,/<svg/);assert.match(nodes.get("scatterChart").innerHTML,/<circle/);console.log("Live catalog smoke test passed");})().catch(error=>{console.error(error);process.exit(1)});
